# 예제 1-3
다음 행렬 $A$, $B$에 대하여 합 $A+B$, 차 $A-B$, 스칼라 곱 $5B$를 구하라.
$$
  A =
  \begin{bmatrix}
    1 & 0 \\
    2 & 1 \\
    4 & 3
  \end{bmatrix}
  ,\quad
  B =
  \begin{bmatrix}
    4 & 3 \\
    1 & 1 \\
    0 & 2
  \end{bmatrix}
$$


In [15]:
import numpy as np

A = np.array([[1, 0], [2, 1], [4, 3]])
B = np.array([[4, 3], [1, 1], [0, 2]])

# A + B 
ApB = A + B

# A - B 
AmB = A - B

# 5B 
sc5B = 5 * B

print("A + B:\n", ApB, "\n")
print("A - B:\n", AmB, "\n")
print("5B:\n", sc5B, "\n")


A + B:
 [[5 3]
 [3 2]
 [4 5]] 

A - B:
 [[-3 -3]
 [ 1  0]
 [ 4  1]] 

5B:
 [[20 15]
 [ 5  5]
 [ 0 10]] 



# 예제 1-4
다음 행렬 $A$, $B$에 대하여 곱 $AB$와 $BA$를 구하라.
$$
  A =
  \begin{bmatrix}
    1 & 2 \\
    3 & 4  
  \end{bmatrix}
  ,\quad
  B =
  \begin{bmatrix}
    5 & 6 \\
    7 & 8
  \end{bmatrix}
$$


In [14]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# AB
AB = np.dot(A, B)

# BA
BA = np.dot(B, A)

print("AB:\n", AB, "\n")
print("BA:\n", BA, "\n")


AB:
 [[19 22]
 [43 50]] 

BA:
 [[23 34]
 [31 46]] 



# 예제 1-5
네 행렬
$$
  A =
  \begin{bmatrix}
    3 & 0 \\
    -1 & 2 \\
    1 & 1   
  \end{bmatrix}
  ,\quad
  B =
  \begin{bmatrix}
    -3 & -1 \\
    2 & 1 \\
    4 & 3
  \end{bmatrix}
  , \quad
  C =
  \begin{bmatrix}
    1 & 2 & 3 \\
    2 & 0 & 1     
  \end{bmatrix}
  , \quad
  D =
  \begin{bmatrix}
    1 \\ 2 \\ 3
  \end{bmatrix}
$$
에 대하여 다음을 계산하여라.

(a) $A + 2B$

(b) $AC$

(c) $3D$

In [13]:
import numpy as np

A = np.array([[3, 0], [-1, 2], [1, 1]])
B = np.array([[-3, -1], [2, 1], [4, 3]])
C = np.array([[1, 2, 3], [2, 0, 1]])
D = np.array([[1], [2], [3]])

# (a) A + 2B
A_plus_2B = A + 2 * B

# (b) AC 
AC = np.dot(A, C)

# (c)
threeD = 3 * D

print("A + 2B:\n", A_plus_2B, "\n")
print("AC:\n", AC, "\n")
print("3D:\n", threeD, "\n")


A + 2B:
 [[-3 -2]
 [ 3  4]
 [ 9  7]] 

AC:
 [[ 3  6  9]
 [ 3 -2 -1]
 [ 3  2  4]] 

3D:
 [[3]
 [6]
 [9]] 



연습문제

주어진 행렬 $A, B, C, D$ 에 대하여 다음을 구하라.
$$
  A =
  \begin{bmatrix}
    1 & 2 \\
    3 & 4  
  \end{bmatrix}
  ,\quad
  B =
  \begin{bmatrix}
    -2 & 4 \\
    1 & 3
  \end{bmatrix}
  , \quad
  C =
  \begin{bmatrix}
    2 & -5 \\
    3 & -2     
  \end{bmatrix}
  , \quad
  D =
  \begin{bmatrix}
    5 & -1 & 3 \\
    -4 & 3 & -6 \\
    -3 & 1 & 2
  \end{bmatrix}
$$

(a) $A[2,2] + B[1,1]$

(e) $(A+B)^{\top}$

(h) $(3I_{3})D$

* $A[2,2]$는 2행 2열의 원소 ($a_{22}$)를 의미
* $I_{n}$은 $n \times n$ 단위행렬을 의미

In [11]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[-2, 4], [1, 3]])
C = np.array([[2, -5], [3, -2]])
D = np.array([[5, -1, 3], [-4, 3, -6], [-3, 1, 2]])

# (a) A[2,2] + B[1,1] 
a = A[1, 1] + B[0, 0]

# (e) (A + B)의 전치 
e = np.transpose(A + B)

# (h) 3*(3x3크기의)단위 행렬*D
I_3 = np.eye(3)  
h = 3 * I_3 @ D

print("A[2,2] + B[1,1]:\n", a, "\n")
print("(A + B)^T:\n", e, "\n")
print("(3I_3)D:\n", h, "\n")


A[2,2] + B[1,1]:
 2 

(A + B)^T:
 [[-1  4]
 [ 6  7]] 

(3I_3)D:
 [[ 15.  -3.   9.]
 [-12.   9. -18.]
 [ -9.   3.   6.]] 

